# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [3]:
import numpy as np

In [12]:
# 1.
zeros = np.array([0,0,0,0,0,0,0,0,0,0])
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [147]:
# 2.
vowels = np.array(["a", "e", "i", "o", "u"])
print(vowels)

['a' 'e' 'i' 'o' 'u']


In [30]:
# 3.
ones = np.array([[1,1,1,1,1],
                [1,1,1,1,1]])
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [321]:
# 4.
myarray1 = np.array([[2.7,0,-2],
             [3.4,10.6,0],
             [-19,99.9,13]])
myarray1

array([[  2.7,   0. ,  -2. ],
       [  3.4,  10.6,   0. ],
       [-19. ,  99.9,  13. ]])

In [437]:
# 5. 
# creates arrays with evenly spaced values
# numpy.arange(start, stop, step, dtype =)

myarray2 = np.arange(4, 4 + 15 * 4, 4, dtype=float) # end on 64, cuz 3 * 5 = 15
myarray2 = myarray2.reshape(3, 5)
myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [179]:
# 1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.
zeros
print("Zeros")
print("Dimensions: " , zeros.ndim)
print("Shape: " , zeros.shape)
print("Size: " , zeros.size)
print("Data Types: " , zeros.dtype)
print("---------------------")
print("Vowels")
print("Dimensions: " , vowels.ndim)
print("Shape: " , vowels.shape)
print("Size: " , vowels.size)
print("Data Types: " , vowels.dtype)
print("---------------------")
print("Ones")
print("Dimensions: " , ones.ndim)
print("Shape: " , ones.shape)
print("Size: " , ones.size)
print("Data Types: " , ones.dtype)
print("---------------------")
print("myarray1")
print("Dimensions: " , myarray1.ndim)
print("Shape: " , myarray1.shape)
print("Size: " , myarray1.size)
print("Data Types: " , myarray1.dtype)
print("---------------------")
print("myarray2")
print("Dimensions: " , myarray2.ndim)
print("Shape: " , myarray2.shape)
print("Size: " , myarray2.size)
print("Data Types: " , myarray2.dtype)

Zeros
Dimensions:  1
Shape:  (10,)
Size:  10
Data Types:  int64
---------------------
Vowels
Dimensions:  1
Shape:  (5,)
Size:  5
Data Types:  <U1
---------------------
Ones
Dimensions:  2
Shape:  (2, 5)
Size:  10
Data Types:  int64
---------------------
myarray1
Dimensions:  2
Shape:  (3, 3)
Size:  9
Data Types:  float64
---------------------
myarray2
Dimensions:  2
Shape:  (3, 5)
Size:  15
Data Types:  float64


In [181]:
# 2. Reshape the array ones to have all the 10 elements in a single row.
print("Ones: " , ones.reshape(1,-1)) # -1; reshapes the array into as many columns
print("myarray1: " , myarray1.reshape(1,-1))
print("myarray2: " , myarray2.reshape(1,-1))

Ones:  [[1 1 1 1 1 1 1 1 1 1]]
myarray1:  [[  2.7   0.   -2.    3.4  10.6   0.  -19.   99.9  13. ]]
myarray2:  [[ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48. 52. 56. 60.]]


In [177]:
# 3. Display the 2nd and 3rd element of the array vowels.
print(vowels[1])
print(vowels[2])

e
i


In [191]:
# 4. Display all elements in the 2nd and 3rd row of the array myarray1.
print(myarray1[1:3]) # 1, second row. 3, not available, so last row. 
                     # myarray1[1:2] gets only the 2nd row.

[[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]


In [207]:
# 5. Display the elements in the 1st and 2nd column of the array myarray1.
print(myarray1[:, 0:2]) # select all rows, and select specific columns

[[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]


In [223]:
# 6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
print(myarray1[1:3, 0]) # 0 means first column

[  3.4 -19. ]


In [399]:
# 7. Reverse the array of vowels.
print(vowels[::-1]) # reverse all elements

['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [237]:
# 1. Divide all elements of array ones by 3.
ones / 3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [307]:
# 2. Add the arrays myarray1 and myarray2.
flat_myarray1 = myarray1.reshape(1, -1)  # (1, 9)
flat_myarray2 = myarray2.reshape(1, -1)  # (1, 15)

myarray2_sliced = flat_myarray2[:, :9]  # slice flat_myarray2 to make it match the nb of elements of myarray1 -> (1,9)

print (flat_myarray1 + myarray2_sliced)

[[  6.7   8.   10.   19.4  30.6  24.    9.  131.9  49. ]]


In [309]:
# 3. Subtract myarray1 from myarray2 and store the result in a new array.
flat_myarray1 = myarray1.reshape(1, -1) 
flat_myarray2 = myarray2.reshape(1, -1)  

myarray2_sliced = flat_myarray2[:, :9]

subtract = flat_myarray1 - myarray2_sliced
print(subtract)

[[ -1.3  -8.  -14.  -12.6  -9.4 -24.  -47.   67.9 -23. ]]


In [337]:
# 4. Multiply myarray1 and myarray2 elementwise.
myarray2_sliced = myarray2[:, :3]  # (3, 3)
print(myarray1 * myarray2_sliced)

[[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]


In [339]:
# 5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
myarray3 = myarray1.dot(myarray2) # no need to transpose
myarray3

array([[ -77.2,  -74.4,  -71.6,  -68.8,  -66. ],
       [ 268. ,  324. ,  380. ,  436. ,  492. ],
       [2893.6, 3269.2, 3644.8, 4020.4, 4396. ]])

In [343]:
# 6. Divide myarray1 by myarray2.
myarray2_sliced = myarray2[:, :3] 
print(myarray1 / myarray2_sliced)

[[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]


In [367]:
# 7. Find the cube of all elements of myarray1 and divide the resulting array by 2.
myarray1_cubed = myarray1 ** 3
myarray1_cubed / 2

array([[ 9.841500e+00,  0.000000e+00, -4.000000e+00],
       [ 1.965200e+01,  5.955080e+02,  0.000000e+00],
       [-3.429500e+03,  4.985015e+05,  1.098500e+03]])

In [383]:
# 8. Find the square root of all elements of myarray2 and divide the resulting array by 2. The result should be rounded to two places of decimals.
myarray2_squareroot = np.sqrt(myarray2)
np.round(myarray2_squareroot / 2, 2)

array([[1.  , 1.41, 1.73, 2.  , 2.24],
       [2.45, 2.65, 2.83, 3.  , 3.16],
       [3.32, 3.46, 3.61, 3.74, 3.87]])

Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [405]:
# 1. Find the transpose of ones and myarray2.
print("Ones: ", ones.T)
print("myarray2: ", myarray2.T)

Ones:  [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
myarray2:  [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]


In [401]:
# 2. Sort the array vowels in reverse.
print(vowels[::-1])

['u' 'o' 'i' 'e' 'a']


In [415]:
# 3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.
np.sort(myarray1, axis = 0) # sorts the array along the first axis of the columns


array([[-19. ,   0. ,  -2. ],
       [  2.7,  10.6,   0. ],
       [  3.4,  99.9,  13. ]])

Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [558]:
myarray4 = np.arange(-1, -1 + 42 * 0.25, 0.25) # 14 * 3 = 42
myarray4.reshape(14,3)
myarray4_split = np.array_split(myarray4, 3) # each array will get 14 elements
myarray4_split_reshaped = [part.reshape(2, 7) for part in myarray4_split] # make each splitted part (2,7)
myarray4_split_reshaped

[array([[-1.  , -0.75, -0.5 , -0.25,  0.  ,  0.25,  0.5 ],
        [ 0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25]]),
 array([[2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ],
        [4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75]]),
 array([[6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 ],
        [7.75, 8.  , 8.25, 8.5 , 8.75, 9.  , 9.25]])]

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

In [560]:
# 1. Find the sum of all elements.
np.sum(myarray4)

173.25

In [568]:
# 2. Find the sum of all elements row wise
row_sum = [np.sum(part, axis=1) for part in myarray4_split_reshaped] # calculates the sum across the columns for each row
row_sum

[array([-1.75, 10.5 ]), array([22.75, 35.  ]), array([47.25, 59.5 ])]

In [570]:
# 3. Find the sum of all elements column wise.
column_sum = [np.sum(part, axis=0) for part in myarray4_split_reshaped] # calculate the sum across the rows for each column
column_sum

[array([-0.25,  0.25,  0.75,  1.25,  1.75,  2.25,  2.75]),
 array([6.75, 7.25, 7.75, 8.25, 8.75, 9.25, 9.75]),
 array([13.75, 14.25, 14.75, 15.25, 15.75, 16.25, 16.75])]

In [572]:
# 4. Find the max of all elements.
np.max(myarray4)

9.25

In [574]:
# 5. Find the min of all elements in each row.
np.min(myarray4)

-1.0

In [584]:
# 6. Find the mean of all elements in each row.
mean = [np.mean(part, axis=1) for part in myarray4_split_reshaped]
mean

[array([-0.25,  1.5 ]), array([3.25, 5.  ]), array([6.75, 8.5 ])]

In [606]:
# 7. Find the standard deviation column wise.
std_devs = [np.std(part, axis=0) for part in myarray4_split_reshaped]
std_devs

[array([0.875, 0.875, 0.875, 0.875, 0.875, 0.875, 0.875]),
 array([0.875, 0.875, 0.875, 0.875, 0.875, 0.875, 0.875]),
 array([0.875, 0.875, 0.875, 0.875, 0.875, 0.875, 0.875])]

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [3]:
import pandas as pd
import numpy as np
ccp = pd.read_csv('country-capital-lat-long-population.csv')

riyadh = ccp[ccp['Country'] == 'Saudi Arabia'][['Latitude', 'Longitude']].values[0] # riyadh coordinates
distances = np.sqrt(np.sum((ccp[['Latitude', 'Longitude']].astype(float) - riyadh) ** 2, axis=1)) # Euclidean distances
closest_index = np.argsort(distances)[1]  # 1 cuz if 0 then it would be riyadh 
closest_capital = ccp.iloc[closest_index] # location of the closest capital

print(f"Capital: {closest_capital['Capital City']}", f", {closest_capital['Country']}")
print(f"Coordinates: {closest_capital['Latitude']}, {closest_capital['Longitude']}")

Capital: Al-Manamah (Manama) , Bahrain
Coordinates: 26.2154, 50.5832


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [9]:
# 1.
import pandas as pd
import numpy as np
ccp = pd.read_csv('country-capital-lat-long-population.csv')

washington_dc = ccp[ccp['Capital City'] == 'Washington'][['Latitude', 'Longitude']] # washington coordinates
distances = np.sqrt(np.sum((ccp[['Latitude', 'Longitude']].astype(float) - washington_dc) ** 2, axis=1)) # Euclidean distances
countries10 = ccp['Country'][np.argsort(distances)[1:11]] # top 10 countries closest to washington, start 1 end 11 to exclude washington

print("Top 10 Countries: \n" , countries10)

Top 10 Countries: 
 148               New Caledonia
149                 New Zealand
150                   Nicaragua
151                       Niger
152                     Nigeria
153                        Niue
154    Northern Mariana Islands
155                      Norway
156                        Oman
157                    Pakistan
Name: Country, dtype: object


In [21]:
# 2. 
import numpy as np
ccp = pd.read_csv('country-capital-lat-long-population.csv')

washington_dc = ccp[ccp['Capital City'] == 'Washington'][['Latitude', 'Longitude']]
distances = np.sqrt(np.sum((ccp[['Latitude', 'Longitude']].astype(float) - washington_dc) ** 2, axis=1)) 
indices = np.argsort(distances)[1:11] 
coordinates_10 = ccp.iloc[indices][['Latitude', 'Longitude']].to_numpy() # NumPy array containing the coordinates of the top 10 cities

print(coordinates_10)

[[ -22.2763  166.4572]
 [ -41.2866  174.7756]
 [  12.1328  -86.2504]
 [  13.5137    2.1098]
 [   9.0574    7.4898]
 [ -19.0585 -169.9213]
 [  15.2123  145.7545]
 [  59.9127   10.7461]
 [  23.6139   58.5922]
 [  33.7035   73.0594]]
